# 1. Nhập các thư viện

In [ ]:
import pandas as pd
import string
import re
import html

# 2. Kiểm tra bộ dữ liệu

## 2.1. Đọc file CSV

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Đường dẫn gốc
root_path = "/content/drive/MyDrive/big_data/phan_1/data/"

# Đọc file CSV
product_df = pd.read_csv(root_path + 'Product.csv', encoding="utf-8")  # <--- product data csv
comment_df = pd.read_csv(root_path + 'Comments.csv', encoding="utf-8") # <--- comments data csv

import os
print(f"Files in {root_path}:")
for dirname, _, filenames in os.walk(root_path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Files in /content/drive/MyDrive/big_data/phan_1/data/:
/content/drive/MyDrive/big_data/phan_1/data/merged_df.csv
/content/drive/MyDrive/big_data/phan_1/data/Product.csv
/content/drive/MyDrive/big_data/phan_1/data/Comments.csv

## 2.2. Xem dữ liệu và thông tin của file sản phẩm

In [ ]:
# Xem 5 dòng đầu của dữ liệu sản phẩm
print("5 rows header of product data")
product_df.head()

5 rows header of product data

            id                                       product_name
0  273456496.0  Tai nghe cho Iphone chân dẹt cao cấp Hoco. M11...
1  248761700.0  Tai nghe bluetooth Rock Retro nghe nhạc liên t...
2  181185263.0  Tai Nghe Baseus Encok 3.5mm lateral in-ear Wir...
3  135410778.0  Ốp Lưng Trong Suốt Hoco Dành Cho iPhone - Hàng...
4  275195798.0  Bộ Máy Retro Gamestick M8 64G 2 tay cầm kết nố...

In [ ]:
# Xem thông tin của dữ liệu sản phẩm
print("Info of product data")
product_df.info()

Info of product data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17064 entries, 0 to 17063
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            17062 non-null  float64
 1   product_name  17064 non-null  object
dtypes: float64(1), object(1)
memory usage: 266.8+ KB

## 2.3. Xem dữ liệu và thông tin của file bình luận

In [ ]:
# Xem 5 dòng đầu của dữ liệu bình luận
print("5 rows header comments data")
comment_df.head()

5 rows header comments data

,comment_id,product_id,customer_id,customer_name,rating,title,content,created_at,purchased_at,seller_id,seller_name
0,19963520,54417619.0,8518691,phạm thị kim thoa,4,Hài lòng,"Xài êm, làm sạch sâu, không gây kích ứng da",1724591314,1.724292e+09,1.0,Tiki Trading
1,8404002,54417619.0,6802843,Truong Ngoc Bich,5,Cực kì hài lòng,"Sản phẩm được giao nhanh chóng, đóng gói kỹ cà...",1615719560,1.615429e+09,120849.0,Nivea Official
2,19560705,54417619.0,19925462,Hàng Thị Hiền,5,Cực kì hài lòng,good,1696061468,1.690178e+09,120849.0,NIVEA OFFICIAL
3,10041860,54417619.0,9906848,Trần Thị Thanh Hằng,5,Cực kì hài lòng,"Mình đã dùng chai thứ 2 rồi, dùng cho tẩy tran...",1622304586,1.621953e+09,120849.0,Nivea Official
4,7118244,54417619.0,15204946,Phùng Ngọc Bình,4,Hài lòng,"k thích mùi này , cảm giác như mùi men tuy nh...",1611158382,1.611051e+09,120849.0,Nivea Official

In [ ]:
# Xem thông tin của dữ liệu bình luận
print("Info of comments data")
comment_df.info()

Info of comments data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348035 entries, 0 to 348034
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   comment_id     348035 non-null  int64
 1   product_id     330686 non-null  float64
 2   customer_id    348035 non-null  int64
 3   customer_name  347595 non-null  object
 4   rating         348035 non-null  int64
 5   title          348017 non-null  object
 6   content        348035 non-null  object
 7   created_at     348035 non-null  int64
 8   purchased_at   344963 non-null  float64
 9   seller_id      346116 non-null  float64
 10  seller_name    346116 non-null  object
dtypes: float64(3), int64(4), object(4)
memory usage: 29.2+ MB

## 2.4. Kiểm tra dữ liệu trùng lặp

## 2.4.1 Kiểm tra dữ liệu trùng lặp trong product_df

In [ ]:
# Kiểm tra các hàng trùng nhau
print("Check duplicate in merged data")
product_df.duplicated(subset='id').sum()

Check duplicate in merged data

np.int64(2163)

In [ ]:
# Xóa các dòng trùng nhau và in ra tổng số dòng còn lại
product_df = product_df.drop_duplicates(subset='id')
print("Số dòng còn lại sau khi xóa các dòng trùng:", product_df.shape[0])

Số dòng còn lại sau khi xóa các dòng trùng: 14901

## 2.4.2 Kiểm tra dữ liệu trùng lặp trong comment_df

In [ ]:
# Kiểm tra các hàng trùng nhau
print("Check duplicate in merged data")
comment_df.duplicated(subset='comment_id').sum()

Check duplicate in merged data

np.int64(9011)

In [ ]:
# Xóa các dòng trùng nhau và in ra tổng số dòng còn lại
comment_df = comment_df.drop_duplicates(subset='comment_id')
print("Số dòng còn lại sau khi xóa các dòng trùng:", comment_df.shape[0])

Số dòng còn lại sau khi xóa các dòng trùng: 339024

# 3. Tích hợp dữ liệu (Inner Join)

In [ ]:
# Ghép 2 file lại bằng inner join
merged_df = pd.merge(
    comment_df,
    product_df,
    left_on="product_id",   # bên comment
    right_on="id",          # bên product
    how="inner"
)
print("Số dòng sau khi inner join:", merged_df.shape[0])

Số dòng sau khi inner join: 336739

In [ ]:
# In ra 5 dòng đầu
merged_df.head()

,comment_id,product_id,customer_id,customer_name,rating,title,content,created_at,purchased_at,seller_id,seller_name,id,product_name
0,19963520,54417619.0,8518691,phạm thị kim thoa,4,Hài lòng,"Xài êm, làm sạch sâu, không gây kích ứng da",1724591314,1.724292e+09,1.0,Tiki Trading,54417619.0,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...
1,8404002,54417619.0,6802843,Truong Ngoc Bich,5,Cực kì hài lòng,"Sản phẩm được giao nhanh chóng, đóng gói kỹ cà...",1615719560,1.615429e+09,120849.0,Nivea Official,54417619.0,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...
2,19560705,54417619.0,19925462,Hàng Thị Hiền,5,Cực kì hài lòng,good,1696061468,1.690178e+09,120849.0,NIVEA OFFICIAL,54417619.0,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...
3,10041860,54417619.0,9906848,Trần Thị Thanh Hằng,5,Cực kì hài lòng,"Mình đã dùng chai thứ 2 rồi, dùng cho tẩy tran...",1622304586,1.621953e+09,120849.0,Nivea Official,54417619.0,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...
4,7118244,54417619.0,15204946,Phùng Ngọc Bình,4,Hài lòng,"k thích mùi này , cảm giác như mùi men tuy nh...",1611158382,1.611051e+09,120849.0,Nivea Official,54417619.0,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...

# 4. Làm sạch dữ liệu

## 4.1. Xóa cột id

In [ ]:
# Xóa cột id
merged_df = merged_df.drop(columns=['id'])

## 4.2. Kiểm tra các giá trị trống

In [ ]:
# Kiểm tra các giá trị trống
print("Check isna in merged data")
merged_df.isna().sum()

Check isna in merged data

comment_id           0
product_id       12664
customer_id          0
customer_name      435
rating               0
title               18
content              0
created_at           0
purchased_at      3052
seller_id         1909
seller_name       1909
product_name         0
dtype: int64

In [ ]:
# Xóa các giá trị trống
merged_df = merged_df.dropna()
# Kiểm tra còn null không
print("Check isna in merged data")
merged_df.isna().sum()

Check isna in merged data

comment_id       0
product_id       0
customer_id      0
customer_name    0
rating           0
title            0
content          0
created_at       0
purchased_at     0
seller_id        0
seller_name      0
product_name     0
dtype: int64

## 4.3. Chuẩn hóa định dạng ngày giờ

In [ ]:
# Chuẩn hóa các trường ngày giờ trong bộ dữ liệu đã gộp
merged_df["created_at"] = pd.to_numeric(merged_df["created_at"], errors='coerce')
merged_df["purchased_at"] = pd.to_numeric(merged_df["purchased_at"], errors='coerce')

# Chuyển đổi với unit='s' (giây)
merged_df["created_at"] = pd.to_datetime(merged_df["created_at"], unit='s')
merged_df["purchased_at"] = pd.to_datetime(merged_df["purchased_at"], unit='s')

print(merged_df[["created_at", "purchased_at"]].head())

           created_at        purchased_at
0 2024-08-25 13:08:34 2024-08-22 02:04:06
1 2021-03-14 10:59:20 2021-03-11 02:18:58
2 2023-09-30 08:11:08 2023-07-24 05:47:07
3 2021-05-29 16:09:46 2021-05-25 14:24:04
4 2021-01-20 15:59:42 2021-01-19 10:03:41

## 4.4. Xử lý ngôn ngữ tự nhiên (NLP)

In [ ]:
def clean_text(text_in: str) -> str:
    """
    Clean & normalize text (Vietnamese-friendly).
    - Remove HTML entities
    - Remove mentions, hashtags, URLs
    - Remove emoji & special symbols
    - Normalize whitespace
    - Keep all words (no stopword / length filtering)
    """

    # 1. Chuyển đổi các ký tự HTML: &amp; → &, &lt; → <
    text_in = html.unescape(text_in)

    # 2. Xóa các đề cập người dùng: @username
    text_in = re.sub(r'@[^\s]+', '', text_in)

    # 3. Chỉ xóa ký hiệu hashtag (#tag → tag)
    text_in = re.sub(r'#(\w+)', r'\1', text_in)

    # 4. Xóa các đường dẫn URL
    text_in = re.sub(r'https?://\S+|www\.\S+', '', text_in)

    # 5. Xóa emoji và các ký hiệu không phải văn bản
    text_in = re.sub(
        r'[\U00010000-\U0010ffff]',
        '',
        text_in
    )

    # 6. Xóa các ký tự đặc biệt (giữ lại chữ cái, số và dấu tiếng Việt)
    text_in = re.sub(r'[^\w\s]', ' ', text_in)

    # 7. Chuẩn hóa khoảng trắng (nhiều khoảng trắng → một khoảng trắng)
    text_in = re.sub(r'\s+', ' ', text_in).strip()

    return text_in

In [ ]:
merged_df['content_text'] = merged_df['content'].apply(clean_text) # Xem trước một số văn bản đã làm sạch
merged_df.head()

,comment_id,product_id,customer_id,customer_name,rating,title,content,created_at,purchased_at,seller_id,seller_name,product_name,content_text
0,19963520,54417619.0,8518691,phạm thị kim thoa,4,Hài lòng,"Xài êm, làm sạch sâu, không gây kích ứng da",2024-08-25 13:08:34,2024-08-22 02:04:06,1.0,Tiki Trading,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...,Xài êm làm sạch sâu không gây kích ứng da
1,8404002,54417619.0,6802843,Truong Ngoc Bich,5,Cực kì hài lòng,"Sản phẩm được giao nhanh chóng, đóng gói kỹ cà...",2021-03-14 10:59:20,2021-03-11 02:18:58,120849.0,Nivea Official,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...,Sản phẩm được giao nhanh chóng đóng gói kỹ càn...
2,19560705,54417619.0,19925462,Hàng Thị Hiền,5,Cực kì hài lòng,good,2023-09-30 08:11:08,2023-07-24 05:47:07,120849.0,NIVEA OFFICIAL,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...,good
3,10041860,54417619.0,9906848,Trần Thị Thanh Hằng,5,Cực kì hài lòng,"Mình đã dùng chai thứ 2 rồi, dùng cho tẩy tran...",2021-05-29 16:09:46,2021-05-25 14:24:04,120849.0,Nivea Official,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...,Mình đã dùng chai thứ 2 rồi dùng cho tẩy trang...
4,7118244,54417619.0,15204946,Phùng Ngọc Bình,4,Hài lòng,"k thích mùi này , cảm giác như mùi men tuy nh...",2021-01-20 15:59:42,2021-01-19 10:03:41,120849.0,Nivea Official,Nước Tẩy Trang NIVEA Pearl Radiant Sáng Da | S...,k thích mùi này cảm giác như mùi men tuy nhiên...

In [ ]:
# Lặp lại nhiều lần với bước sau
import pandas as pd
from collections import Counter
import re

def stats_short_words_df(df, text_col, min_len=1, max_len=2, top_k=50):
    """
    Thống kê các từ có độ dài từ min_len đến max_len.
    """
    counter = Counter()

    for text in df[text_col]:
        # Kiểm tra dữ liệu rỗng hoặc không phải chuỗi
        if pd.isna(text) or not isinstance(text, str):
            continue

        # 1. Chuyển về chữ thường
        text = text.lower()

        # 2. Dùng Regex để chỉ lấy chữ cái và số (loại bỏ dấu câu)
        # \w+ nghĩa là lấy các cụm từ liền mạch
        words = re.findall(r'\w+', text)

        # 3. Lọc độ dài từ
        short_words = [w for w in words if min_len <= len(w) <= max_len]

        # 4. Cập nhật vào bộ đếm
        counter.update(short_words)

    return counter.most_common(top_k)

# --- CÁCH SỬ DỤNG ---
# Giả sử bạn có DataFrame là merged_df
top_words = stats_short_words_df(merged_df, "content_text", top_k=2000)

print("--- CÁC TỪ NGẮN XUẤT HIỆN NHIỀU NHẤT ---")
for word, freq in top_words:
    print(f"Từ '{word}': xuất hiện {freq} lần")

--- CÁC TỪ NGẮN XUẤT HIỆN NHIỀU NHẤT ---
Từ 'có': xuất hiện 61316 lần
Từ 'và': xuất hiện 54927 lần
Từ 'là': xuất hiện 44082 lần
Từ 'ok': xuất hiện 34958 lần
Từ 'bị': xuất hiện 28984 lần
Từ 'về': xuất hiện 24739 lần
Từ 'mà': xuất hiện 24721 lần
Từ 'đã': xuất hiện 24419 lần
Từ 'ko': xuất hiện 21379 lần
Từ 'để': xuất hiện 20473 lần
Từ '1': xuất hiện 18263 lần
Từ 'sẽ': xuất hiện 17221 lần
Từ 'ổn': xuất hiện 13559 lần
Từ 'dễ': xuất hiện 13354 lần
Từ 'ra': xuất hiện 13138 lần
Từ 'da': xuất hiện 12779 lần
Từ 'vì': xuất hiện 11952 lần
Từ 'cả': xuất hiện 11234 lần
Từ 'gì': xuất hiện 10939 lần
Từ 'k': xuất hiện 10387 lần
Từ '2': xuất hiện 10281 lần
Từ 'sử': xuất hiện 10266 lần
Từ 'ạ': xuất hiện 10191 lần
Từ 'sự': xuất hiện 10187 lần
Từ 'ý': xuất hiện 9773 lần
Từ 'từ': xuất hiện 9686 lần
Từ 'nó': xuất hiện 9190 lần
Từ 'ở': xuất hiện 8991 lần
Từ 'sp': xuất hiện 8453 lần
Từ 'ơn': xuất hiện 8450 lần
Từ 'đi': xuất hiện 7651 lần
Từ 'đó': xuất hiện 7324 lần
Từ 'đc': xuất hiện 7308 lần
Từ 'in': xuất hiện 6431 lần
Từ '5': xuất hiện 6388 lần
Từ 'ng': xuất hiện 6183 lần
Từ 'rẻ': xuất hiện 5827 lần
Từ 'ta': xuất hiện 5809 lần
Từ 'hộ': xuất hiện 5781 lần
Từ 'lý': xuất hiện 5679 lần
Từ '3': xuất hiện 5565 lần
Từ 'n': xuất hiện 5407 lần
Từ 't': xuất hiện 5231 lần
Từ 'do': xuất hiện 5140 lần
Từ 'rõ': xuất hiện 5059 lần
Từ 'i': xuất hiện 5034 lần
Từ 'ai': xuất hiện 4745 lần
Từ 'kĩ': xuất hiện 4725 lần
Từ 'so': xuất hiện 4588 lần
Từ 'đề': xuất hiện 4558 lần
Từ 'kỹ': xuất hiện 4507 lần
Từ 'dù': xuất hiện 4502 lần
Từ 'em': xuất hiện 4289 lần
Từ 'độ': xuất hiện 4142 lần
Từ 'đủ': xuất hiện 4073 lần
Từ 'tả': xuất hiện 4064 lần
Từ 'êm': xuất hiện 3951 lần
Từ 'số': xuất hiện 3852 lần
Từ 'c': xuất hiện 3670 lần
Từ 'bé': xuất hiện 3550 lần
Từ 'áo': xuất hiện 3453 lần
Từ 'mô': xuất hiện 3265 lần
Từ 'tự': xuất hiện 3245 lần
Từ 'to': xuất hiện 3203 lần
Từ 'm': xuất hiện 3189 lần
Từ 'vô': xuất hiện 3156 lần
Từ 'vụ': xuất hiện 3021 lần
Từ 'kì': xuất hiện 3012 lần
Từ 'cũ': xuất hiện 3009 lần
Từ 'tư': xuất hiện 2952 lần
Từ 'vị': xuất hiện 2952 lần
Từ 'mở': xuất hiện 2945 lần
Từ '4': xuất hiện 2850 lần
Từ 'y': xuất hiện 2843 lần
Từ 'dự': xuất hiện 2832 lần
Từ 'bổ': xuất hiện 2744 lần
Từ '10': xuất hiện 2707 lần
Từ 'bỏ': xuất hiện 2707 lần
Từ 'bộ': xuất hiện 2699 lần
Từ 'mơ': xuất hiện 2600 lần
Từ 'kỳ': xuất hiện 2513 lần
Từ 'cứ': xuất hiện 2499 lần
Từ 'dc': xuất hiện 2497 lần
Từ 'ít': xuất hiện 2361 lần
Từ 'tệ': xuất hiện 2314 lần
Từ 'a': xuất hiện 2272 lần
Từ 'mn': xuất hiện 2223 lần
Từ 'cơ': xuất hiện 2200 lần
Từ 'tế': xuất hiện 2195 lần
Từ 'mã': xuất hiện 2083 lần
Từ 'áp': xuất hiện 2059 lần
Từ 'nh': xuất hiện 2048 lần
Từ 'sơ': xuất hiện 2038 lần
Từ 'hư': xuất hiện 1977 lần
Từ 'co': xuất hiện 1971 lần
Từ 'u': xuất hiện 1954 lần
Từ 'ẩm': xuất hiện 1936 lần
Từ 'ấn': xuất hiện 1934 lần
Từ 'ấy': xuất hiện 1862 lần
Từ 'âm': xuất hiện 1861 lần
Từ 'vẻ': xuất hiện 1852 lần
Từ 'ăn': xuất hiện 1838 lần
Từ 'ch': xuất hiện 1766 lần
Từ 'xa': xuất hiện 1763 lần
Từ 'bì': xuất hiện 1736 lần
Từ 'đo': xuất hiện 1725 lần
Từ 'sa': xuất hiện 1725 lần
Từ 'kể': xuất hiện 1705 lần
Từ 'mẹ': xuất hiện 1675 lần
Từ 'đồ': xuất hiện 1579 lần
Từ 'la': xuất hiện 1576 lần
Từ 'kế': xuất hiện 1553 lần
Từ 'va': xuất hiện 1506 lần
Từ 'p': xuất hiện 1487 lần
Từ 'á': xuất hiện 1486 lần
Từ 'lẽ': xuất hiện 1473 lần
Từ 'ví': xuất hiện 1429 lần
Từ 'ha': xuất hiện 1428 lần
Từ 'lí': xuất hiện 1411 lần
Từ 'vs': xuất hiện 1384 lần
Từ 'tí': xuất hiện 1378 lần
Từ 'cô': xuất hiện 1368 lần
Từ 'hệ': xuất hiện 1352 lần
Từ 'an': xuất hiện 1342 lần
Từ 'đỡ': xuất hiện 1290 lần
Từ 'hy': xuất hiện 1283 lần
Từ 'đa': xuất hiện 1279 lần
Từ 'hi': xuất hiện 1266 lần
Từ 'r': xuất hiện 1260 lần
Từ 'sợ': xuất hiện 1225 lần
Từ 'mê': xuất hiện 1219 lần
Từ 'ba': xuất hiện 1210 lần
Từ 'cá': xuất hiện 1166 lần
Từ 'ca': xuất hiện 1164 lần
Từ 'họ': xuất hiện 1152 lần
Từ 'hỗ': xuất hiện 1128 lần
Từ 'ơi': xuất hiện 1119 lần
Từ 'hề': xuất hiện 1099 lần
Từ 'cố': xuất hiện 1084 lần
Từ 'uy': xuất hiện 1069 lần
Từ 'ma': xuất hiện 1036 lần
Từ 'nè': xuất hiện 1034 lần
Từ 'dơ': xuất hiện 1034 lần
Từ 'mk': xuất hiện 1023 lần
Từ 'lo': xuất hiện 1022 lần
Từ '6': xuất hiện 1016 lần
Từ 'cu': xuất hiện 977 lần
Từ 'e': xuất hiện 971 lần
Từ 'mi': xuất hiện 951 lần
Từ 'vệ': xuất hiện 927 lần
Từ '7': xuất hiện 926 lần
Từ 'râ': xuất hiện 889 lần
Từ 'o': xuất hiện 883 lần
Từ 'tô': xuất hiện 879 lần
Từ 'du': xuất hiện 878 lần
Từ 'dị': xuất hiện 870 lần
Từ 'vỏ': xuất hiện 867 lần
Từ 'gõ': xuất hiện 859 lần
Từ 'lạ': xuất hiện 851 lần
Từ 'kh': xuất hiện 842 lần
Từ 'j': xuất hiện 812 lần
Từ 'ồn': xuất hiện 783 lần
Từ 'di': xuất hiện 783 lần
Từ 'xử': xuất hiện 779 lần
Từ 'bí': xuất hiện 776 lần
Từ 'sd': xuất hiện 769 lần
Từ 'v': xuất hiện 769 lần
Từ 'lọ': xuất hiện 763 lần
Từ 'bi': xuất hiện 755 lần
Từ 'cụ': xuất hiện 750 lần
Từ 'nữ': xuất hiện 747 lần
Từ 'vũ': xuất hiện 719 lần
Từ 'mỹ': xuất hiện 712 lần
Từ 'bố': xuất hiện 712 lần
Từ 'đỏ': xuất hiện 695 lần
Từ 'cổ': xuất hiện 675 lần
Từ 'ẩn': xuất hiện 671 lần
Từ 'tử': xuất hiện 666 lần
Từ '8': xuất hiện 665 lần
Từ 'dụ': xuất hiện 664 lần
Từ 'sư': xuất hiện 649 lần
Từ 'vi': xuất hiện 640 lần
Từ 'đổ': xuất hiện 631 lần
Từ 'bà': xuất hiện 630 lần
Từ '12': xuất hiện 626 lần
Từ 's': xuất hiện 623 lần
Từ 'à': xuất hiện 619 lần
Từ '9': xuất hiện 619 lần
Từ 'ho': xuất hiện 606 lần
Từ 'mờ': xuất hiện 605 lần
Từ 'na': xuất hiện 587 lần
Từ 'sẻ': xuất hiện 586 lần
Từ 'vẽ': xuất hiện 572 lần
Từ 'kg': xuất hiện 565 lần
Từ 'xã': xuất hiện 564 lần
Từ 'ký': xuất hiện 563 lần
Từ 'd': xuất hiện 553 lần
Từ 'ưu': xuất hiện 553 lần
Từ 'đê': xuất hiện 549 lần
Từ 'tờ': xuất hiện 534 lần
Từ '11': xuất hiện 532 lần
Từ 'í': xuất hiện 531 lần
Từ '2h': xuất hiện 521 lần
Từ 'ấm': xuất hiện 520 lần
Từ 'ti': xuất hiện 518 lần
Từ 'sổ': xuất hiện 514 lần
Từ 'su': xuất hiện 505 lần
Từ '50': xuất hiện 504 lần
Từ 'h': xuất hiện 499 lần
Từ 'nạ': xuất hiện 498 lần
Từ 'xò': xuất hiện 494 lần
Từ 'se': xuất hiện 491 lần
Từ 'ôm': xuất hiện 482 lần
Từ 'ẩu': xuất hiện 477 lần
Từ 'cx': xuất hiện 469 lần
Từ 'bè': xuất hiện 468 lần
Từ 'vỡ': xuất hiện 466 lần
Từ 'đe': xuất hiện 465 lần
Từ 'mồ': xuất hiện 462 lần
Từ 'ốp': xuất hiện 462 lần
Từ 'bt': xuất hiện 459 lần
Từ 'mẻ': xuất hiện 454 lần
Từ 'bề': xuất hiện 451 lần
Từ 'cỡ': xuất hiện 446 lần
Từ 'án': xuất hiện 446 lần
Từ '20': xuất hiện 442 lần
Từ 'no': xuất hiện 435 lần
Từ '0': xuất hiện 433 lần
Từ 'vơ': xuất hiện 430 lần
Từ 'l': xuất hiện 429 lần
Từ 'mò': xuất hiện 423 lần
Từ 'sờ': xuất hiện 416 lần
Từ 'go': xuất hiện 411 lần
Từ 'sĩ': xuất hiện 408 lần
Từ 'hà': xuất hiện 398 lần
Từ 'sở': xuất hiện 395 lần
Từ 'kỷ': xuất hiện 392 lần
Từ 'nd': xuất hiện 376 lần
Từ 'câ': xuất hiện 374 lần
Từ 'on': xuất hiện 371 lần
Từ 'tò': xuất hiện 367 lần
Từ 'hồ': xuất hiện 366 lần
Từ '30': xuất hiện 365 lần
Từ 'củ': xuất hiện 358 lần
Từ 'kẻ': xuất hiện 357 lần
Từ 'vn': xuất hiện 356 lần
Từ 'xu': xuất hiện 353 lần
Từ 'tủ': xuất hiện 353 lần
Từ 'ah': xuất hiện 349 lần
Từ 'bù': xuất hiện 347 lần
Từ 'xl': xuất hiện 345 lần
Từ 'lỗ': xuất hiện 342 lần
Từ 'dở': xuất hiện 337 lần
Từ 'đô': xuất hiện 325 lần
Từ 'mo': xuất hiện 321 lần
Từ 'dữ': xuất hiện 321 lần
Từ 'tố': xuất hiện 317 lần
Từ 'xe': xuất hiện 314 lần
Từ 'hô': xuất hiện 310 lần
Từ 'vợ': xuất hiện 308 lần
Từ 'ái': xuất hiện 308 lần
Từ 'ty': xuất hiện 300 lần
Từ 'vê': xuất hiện 298 lần
Từ 'lỡ': xuất hiện 297 lần
Từ 'dã': xuất hiện 291 lần
Từ 'ly': xuất hiện 290 lần
Từ 'kí': xuất hiện 287 lần
Từ 'mó': xuất hiện 284 lần
Từ '15': xuất hiện 280 lần
Từ 'dê': xuất hiện 279 lần
Từ 'xả': xuất hiện 277 lần
Từ 'bo': xuất hiện 274 lần
Từ 'cư': xuất hiện 272 lần
Từ 'ám': xuất hiện 269 lần
Từ 'đu': xuất hiện 268 lần
Từ 'g': xuất hiện 265 lần
Từ 'lẹ': xuất hiện 262 lần
Từ 'up': xuất hiện 257 lần
Từ 'mă': xuất hiện 256 lần
Từ 'vâ': xuất hiện 254 lần
Từ 'gi': xuất hiện 253 lần
Từ 'nv': xuất hiện 252 lần
Từ 'tớ': xuất hiện 251 lần
Từ 'ki': xuất hiện 249 lần
Từ 'ô': xuất hiện 248 lần
Từ 'kỉ': xuất hiện 246 lần
Từ 'mẽ': xuất hiện 244 lần
Từ 'lẻ': xuất hiện 243 lần
Từ 'xơ': xuất hiện 243 lần
Từ 'it': xuất hiện 239 lần
Từ 'kê': xuất hiện 236 lần
Từ 'ố': xuất hiện 235 lần
Từ 'tu': xuất hiện 233 lần
Từ 'b': xuất hiện 232 lần
Từ 'df': xuất hiện 232 lần
Từ 'nô': xuất hiện 231 lần
Từ 'đế': xuất hiện 231 lần
Từ 'lộ': xuất hiện 230 lần
Từ 'đơ': xuất hiện 229 lần
Từ 'ni': xuất hiện 226 lần
Từ 'dư': xuất hiện 225 lần
Từ 'sò': xuất hiện 222 lần
Từ 'đâ': xuất hiện 221 lần
Từ 'hè': xuất hiện 219 lần
Từ 'de': xuất hiện 218 lần
Từ 'đt': xuất hiện 216 lần
Từ '25': xuất hiện 214 lần
Từ 'kệ': xuất hiện 214 lần
Từ 'lê': xuất hiện 213 lần
Từ 'lâ': xuất hiện 211 lần
Từ 'km': xuất hiện 209 lần
Từ 'ms': xuất hiện 208 lần
Từ 'xứ': xuất hiện 204 lần
Từ 'âu': xuất hiện 202 lần
Từ 'vĩ': xuất hiện 199 lần
Từ 'lệ': xuất hiện 198 lần
Từ 'li': xuất hiện 197 lần
Từ 'lì': xuất hiện 197 lần
Từ 'ae': xuất hiện 197 lần
Từ 'rè': xuất hiện 196 lần
Từ 've': xuất hiện 195 lần
Từ 'ôn': xuất hiện 194 lần
Từ 'ép': xuất hiện 191 lần
Từ 'iu': xuất hiện 190 lần
Từ 'đẽ': xuất hiện 190 lần
Từ 'me': xuất hiện 190 lần
Từ 'tỉ': xuất hiện 187 lần
Từ 'gu': xuất hiện 187 lần
Từ 'ảo': xuất hiện 187 lần
Từ 'sx': xuất hiện 186 lần
Từ 'dạ': xuất hiện 186 lần
Từ 'ức': xuất hiện 185 lần
Từ 'dí': xuất hiện 184 lần
Từ 'rô': xuất hiện 182 lần
Từ 'bó': xuất hiện 180 lần
Từ 'tý': xuất hiện 180 lần
Từ '13': xuất hiện 179 lần
Từ 'x': xuất hiện 174 lần
Từ 'be': xuất hiện 174 lần
Từ 'cờ': xuất hiện 174 lần
Từ 'qr': xuất hiện 171 lần
Từ '18': xuất hiện 170 lần
Từ 'dể': xuất hiện 170 lần
Từ 'cú': xuất hiện 170 lần
Từ '40': xuất hiện 170 lần
Từ 'sô': xuất hiện 169 lần
Từ 'nỗ': xuất hiện 169 lần
Từ 'cử': xuất hiện 168 lần
Từ 'gỡ': xuất hiện 167 lần
Từ 'ôi': xuất hiện 167 lần
Từ '24': xuất hiện 166 lần
Từ '16': xuất hiện 166 lần
Từ 'ư': xuất hiện 165 lần
Từ 'vu': xuất hiện 163 lần
Từ 'cà': xuất hiện 163 lần
Từ 'z': xuất hiện 159 lần
Từ 'bể': xuất hiện 158 lần
Từ 'lơ': xuất hiện 154 lần
Từ 'im': xuất hiện 153 lần
Từ 'bự': xuất hiện 153 lần
Từ 'hả': xuất hiện 153 lần
Từ 'mộ': xuất hiện 153 lần
Từ 're': xuất hiện 152 lần
Từ 'nx': xuất hiện 152 lần
Từ 'of': xuất hiện 150 lần
Từ 'tâ': xuất hiện 150 lần
Từ 'xé': xuất hiện 150 lần
Từ 'lá': xuất hiện 149 lần
Từ 'tơ': xuất hiện 148 lần
Từ 'đk': xuất hiện 148 lần
Từ 'hê': xuất hiện 148 lần
Từ 'dâ': xuất hiện 148 lần
Từ 'đă': xuất hiện 145 lần
Từ 'tp': xuất hiện 144 lần
Từ '14': xuất hiện 144 lần
Từ 'lă': xuất hiện 143 lần
Từ '17': xuất hiện 143 lần
Từ 'tg': xuất hiện 142 lần
Từ 'ơ': xuất hiện 142 lần
Từ 'ác': xuất hiện 142 lần
Từ 'ak': xuất hiện 141 lần
Từ 'mỉ': xuất hiện 141 lần
Từ 'dk': xuất hiện 140 lần
Từ 'hở': xuất hiện 140 lần
Từ 'hơ': xuất hiện 139 lần
Từ 'tỏ': xuất hiện 139 lần
Từ 'bồ': xuất hiện 138 lần
Từ 'is': xuất hiện 137 lần
Từ 'vo': xuất hiện 136 lần
Từ 'hn': xuất hiện 134 lần
Từ 'mu': xuất hiện 134 lần
Từ 'pc': xuất hiện 134 lần
Từ '80': xuất hiện 132 lần
Từ 'dĩ': xuất hiện 132 lần
Từ 'ky': xuất hiện 131 lần
Từ 'ổ': xuất hiện 131 lần
Từ '21': xuất hiện 130 lần
Từ '33': xuất hiện 130 lần
Từ 'ro': xuất hiện 129 lần
Từ 'nc': xuất hiện 128 lần
Từ 'bh': xuất hiện 128 lần
Từ 'đá': xuất hiện 127 lần
Từ 'nư': xuất hiện 126 lần
Từ 'vớ': xuất hiện 126 lần
Từ '19': xuất hiện 123 lần
Từ 'tr': xuất hiện 122 lần
Từ '_': xuất hiện 120 lần
Từ 'hổ': xuất hiện 120 lần
Từ 'tổ': xuất hiện 119 lần
Từ 'sứ': xuất hiện 119 lần
Từ '70': xuất hiện 118 lần
Từ 'lô': xuất hiện 118 lần
Từ 'ui': xuất hiện 117 lần
Từ 'mĩ': xuất hiện 117 lần
Từ 'vư': xuất hiện 117 lần
Từ 'qc': xuất hiện 116 lần
Từ 'hủ': xuất hiện 116 lần
Từ 'tì': xuất hiện 116 lần
Từ 'cn': xuất hiện 116 lần
Từ 'óc': xuất hiện 116 lần
Từ 'tê': xuất hiện 115 lần
Từ 'sả': xuất hiện 115 lần
Từ 'le': xuất hiện 115 lần
Từ 'â': xuất hiện 114 lần
Từ '60': xuất hiện 114 lần
Từ 'lm': xuất hiện 112 lần
Từ '22': xuất hiện 112 lần
Từ 'dẻ': xuất hiện 111 lần
Từ 'xi': xuất hiện 111 lần
Từ 'đ': xuất hiện 110 lần
Từ 'lu': xuất hiện 110 lần
Từ 'bò': xuất hiện 110 lần
Từ '4g': xuất hiện 110 lần
Từ 't2': xuất hiện 109 lần
Từ 'hạ': xuất hiện 109 lần
Từ 'ủ': xuất hiện 108 lần
Từ 'cs': xuất hiện 108 lần
Từ 'mâ': xuất hiện 106 lần
Từ 'mh': xuất hiện 106 lần
Từ 'vả': xuất hiện 106 lần
Từ 'ẹp': xuất hiện 104 lần
Từ 'ad': xuất hiện 103 lần
Từ 'lễ': xuất hiện 103 lần
Từ 'ck': xuất hiện 103 lần
Từ '1h': xuất hiện 102 lần
Từ 'dè': xuất hiện 102 lần
Từ 'vã': xuất hiện 102 lần
Từ '9h': xuất hiện 99 lần
Từ 'ao': xuất hiện 99 lần
Từ 'xà': xuất hiện 97 lần
Từ 'ưa': xuất hiện 97 lần
Từ 'ke': xuất hiện 97 lần
Từ '01': xuất hiện 97 lần
Từ 'đè': xuất hiện 97 lần
Từ 'he': xuất hiện 96 lần
Từ 'tù': xuất hiện 96 lần
Từ '23': xuất hiện 95 lần
Từ 'rv': xuất hiện 95 lần
Từ 'đà': xuất hiện 95 lần
Từ 'nọ': xuất hiện 94 lần
Từ 'xù': xuất hiện 94 lần
Từ 'hk': xuất hiện 93 lần
Từ 'bế': xuất hiện 93 lần
Từ 'ph': xuất hiện 93 lần
Từ 'xí': xuất hiện 93 lần
Từ 'má': xuất hiện 92 lần
Từ 'ọp': xuất hiện 91 lần
Từ 'rỡ': xuất hiện 91 lần
Từ 'am': xuất hiện 90 lần
Từ 'kẽ': xuất hiện 90 lần
Từ 'bê': xuất hiện 89 lần
Từ 'ê': xuất hiện 88 lần
Từ 'ru': xuất hiện 88 lần
Từ 'nổ': xuất hiện 87 lần
Từ 'hũ': xuất hiện 86 lần
Từ 'ẻm': xuất hiện 86 lần
Từ 'nê': xuất hiện 85 lần
Từ 'rỉ': xuất hiện 85 lần
Từ 'hu': xuất hiện 85 lần
Từ 'nở': xuất hiện 84 lần
Từ 'tv': xuất hiện 84 lần
Từ 'xì': xuất hiện 84 lần
Từ '29': xuất hiện 84 lần
Từ 'ân': xuất hiện 83 lần
Từ 'lg': xuất hiện 82 lần
Từ 'my': xuất hiện 81 lần
Từ 'nề': xuất hiện 81 lần
Từ 'ny': xuất hiện 80 lần
Từ 'vở': xuất hiện 80 lần
Từ 'oi': xuất hiện 79 lần
Từ 'ủa': xuất hiện 78 lần
Từ 'ươ': xuất hiện 78 lần
Từ '28': xuất hiện 77 lần
Từ 'ấu': xuất hiện 77 lần
Từ '2m': xuất hiện 77 lần
Từ '5s': xuất hiện 76 lần
Từ 'bn': xuất hiện 76 lần
Từ 'vl': xuất hiện 76 lần
Từ '90': xuất hiện 76 lần
Từ 'vỗ': xuất hiện 76 lần
Từ 'să': xuất hiện 76 lần
Từ '8h': xuất hiện 75 lần
Từ 'nà': xuất hiện 75 lần
Từ 'rê': xuất hiện 75 lần
Từ 'lò': xuất hiện 75 lần
Từ 'sỹ': xuất hiện 75 lần
Từ 'võ': xuất hiện 74 lần
Từ '27': xuất hiện 74 lần
Từ 'b5': xuất hiện 74 lần
Từ 'bô': xuất hiện 73 lần
Từ 'vc': xuất hiện 73 lần
Từ 'lồ': xuất hiện 73 lần
Từ 'ne': xuất hiện 72 lần
Từ 'te': xuất hiện 72 lần
Từ 'bâ': xuất hiện 72 lần
Từ 'tq': xuất hiện 71 lần
Từ '3h': xuất hiện 71 lần
Từ 'ủi': xuất hiện 71 lần
Từ 'rẽ': xuất hiện 70 lần
Từ 'ns': xuất hiện 70 lần
Từ 'lề': xuất hiện 70 lần
Từ 't7': xuất hiện 69 lần
Từ 'sg': xuất hiện 69 lần
Từ 'ip': xuất hiện 69 lần
Từ 'tă': xuất hiện 67 lần
Từ 'cd': xuất hiện 67 lần
Từ 'kk': xuất hiện 67 lần
Từ 'wa': xuất hiện 66 lần
Từ 'hs': xuất hiện 66 lần
Từ 'ga': xuất hiện 65 lần
Từ 'qá': xuất hiện 65 lần
Từ 'xô': xuất hiện 65 lần
Từ 'gh': xuất hiện 64 lần
Từ 'bã': xuất hiện 64 lần
Từ 'rà': xuất hiện 64 lần
Từ '02': xuất hiện 64 lần
Từ 'vd': xuất hiện 64 lần
Từ 'đư': xuất hiện 63 lần
Từ '99': xuất hiện 62 lần
Từ 'ào': xuất hiện 62 lần
Từ 'mù': xuất hiện 62 lần
Từ 'tn': xuất hiện 61 lần
Từ 'cỏ': xuất hiện 61 lần
Từ 'bờ': xuất hiện 61 lần
Từ 't3': xuất hiện 60 lần
Từ 'nt': xuất hiện 60 lần
Từ '31': xuất hiện 60 lần
Từ 'ôk': xuất hiện 60 lần
Từ '1m': xuất hiện 60 lần
Từ '26': xuất hiện 60 lần
Từ 'gà': xuất hiện 60 lần
Từ 'lư': xuất hiện 60 lần
Từ 'tt': xuất hiện 59 lần
Từ 'si': xuất hiện 59 lần
Từ 'by': xuất hiện 58 lần
Từ 'nă': xuất hiện 58 lần
Từ 'bỉ': xuất hiện 58 lần
Từ 'dỗ': xuất hiện 58 lần
Từ 'bẻ': xuất hiện 58 lần
Từ 'kb': xuất hiện 57 lần
Từ '03': xuất hiện 57 lần
Từ 'nể': xuất hiện 57 lần
Từ 'ốc': xuất hiện 56 lần
Từ 'bá': xuất hiện 56 lần
Từ 'rũ': xuất hiện 56 lần
Từ 'bơ': xuất hiện 56 lần
Từ 'sz': xuất hiện 56 lần
Từ 'mũ': xuất hiện 55 lần
Từ '09': xuất hiện 55 lần
Từ 'gâ': xuất hiện 55 lần
Từ '35': xuất hiện 55 lần
Từ 't6': xuất hiện 55 lần
Từ 'đỗ': xuất hiện 55 lần
Từ 'tỷ': xuất hiện 55 lần
Từ '42': xuất hiện 55 lần
Từ 'hú': xuất hiện 54 lần
Từ 'gă': xuất hiện 54 lần
Từ '45': xuất hiện 54 lần
Từ '07': xuất hiện 54 lần
Từ 'mớ': xuất hiện 54 lần
Từ 'hp': xuất hiện 54 lần
Từ 'q': xuất hiện 53 lần
Từ 'vé': xuất hiện 53 lần
Từ 'kq': xuất hiện 52 lần
Từ 'hí': xuất hiện 52 lần
Từ 'bă': xuất hiện 52 lần
Từ 'tc': xuất hiện 51 lần
Từ 'cm': xuất hiện 51 lần
Từ 'hé': xuất hiện 50 lần
Từ 'pr': xuất hiện 50 lần
Từ 'út': xuất hiện 50 lần
Từ 'đx': xuất hiện 49 lần
Từ 'th': xuất hiện 49 lần
Từ 'dt': xuất hiện 48 lần
Từ 'f': xuất hiện 48 lần
Từ 'dế': xuất hiện 48 lần
Từ 't4': xuất hiện 47 lần
Từ 'nỡ': xuất hiện 46 lần
Từ 'nẻ': xuất hiện 46 lần
Từ '05': xuất hiện 46 lần
Từ 'sộ': xuất hiện 46 lần
Từ 'át': xuất hiện 45 lần
Từ 'gg': xuất hiện 45 lần
Từ 'dv': xuất hiện 45 lần
Từ 'jo': xuất hiện 45 lần
Từ 'tứ': xuất hiện 45 lần
Từ 'nợ': xuất hiện 45 lần
Từ 'lổ': xuất hiện 44 lần
Từ 'mỡ': xuất hiện 43 lần
Từ 'or': xuất hiện 43 lần
Từ 'cg': xuất hiện 43 lần
Từ 'đg': xuất hiện 43 lần
Từ 'sn': xuất hiện 43 lần
Từ 'gù': xuất hiện 43 lần
Từ 'tạ': xuất hiện 43 lần
Từ 'nụ': xuất hiện 43 lần
Từ 'đẻ': xuất hiện 42 lần
Từ 'aa': xuất hiện 42 lần
Từ '36': xuất hiện 42 lần
Từ '4h': xuất hiện 42 lần
Từ 'hd': xuất hiện 42 lần
Từ 'vv': xuất hiện 42 lần
Từ 'dô': xuất hiện 42 lần
Từ 'gỗ': xuất hiện 42 lần
Từ 'gs': xuất hiện 42 lần
Từ 'pk': xuất hiện 41 lần
Từ '04': xuất hiện 41 lần
Từ 'sv': xuất hiện 41 lần
Từ 'xá': xuất hiện 41 lần
Từ '3m': xuất hiện 41 lần
Từ 'bu': xuất hiện 41 lần
Từ '4k': xuất hiện 40 lần
Từ 'hh': xuất hiện 40 lần
Từ 'ké': xuất hiện 40 lần
Từ 'lũ': xuất hiện 40 lần
Từ 'rỏ': xuất hiện 40 lần
Từ 'nộ': xuất hiện 40 lần
Từ 'hì': xuất hiện 39 lần
Từ 'cọ': xuất hiện 39 lần
Từ 'ấp': xuất hiện 39 lần
Từ 'tk': xuất hiện 38 lần
Từ '65': xuất hiện 38 lần
Từ 'kt': xuất hiện 38 lần
Từ 'rì': xuất hiện 37 lần
Từ '5m': xuất hiện 37 lần
Từ '08': xuất hiện 36 lần
Từ 'qa': xuất hiện 36 lần
Từ 'dì': xuất hiện 36 lần
Từ '55': xuất hiện 36 lần
Từ 'tè': xuất hiện 35 lần
Từ 'lố': xuất hiện 35 lần
Từ '48': xuất hiện 35 lần
Từ '5k': xuất hiện 35 lần
Từ '06': xuất hiện 35 lần
Từ 'tá': xuất hiện 35 lần
Từ 'bọ': xuất hiện 35 lần
Từ 'mị': xuất hiện 35 lần
Từ 'pp': xuất hiện 35 lần
Từ 'a4': xuất hiện 35 lần
Từ 'mỏ': xuất hiện 34 lần
Từ '00': xuất hiện 34 lần
Từ 'rễ': xuất hiện 34 lần
Từ 'ạh': xuất hiện 34 lần
Từ 'eo': xuất hiện 34 lần
Từ 'hă': xuất hiện 33 lần
Từ 'as': xuất hiện 33 lần
Từ 'dò': xuất hiện 33 lần
Từ '5p': xuất hiện 33 lần
Từ 'rỗ': xuất hiện 33 lần
Từ '5h': xuất hiện 33 lần
Từ 'đh': xuất hiện 33 lần
Từ 'gò': xuất hiện 33 lần
Từ 'hố': xuất hiện 32 lần
Từ 'bs': xuất hiện 32 lần
Từ 'pa': xuất hiện 32 lần
Từ 'mè': xuất hiện 32 lần
Từ 'mí': xuất hiện 32 lần
Từ '32': xuất hiện 32 lần
Từ '3d': xuất hiện 32 lần
Từ 'lờ': xuất hiện 32 lần
Từ 'ồ': xuất hiện 32 lần
Từ 'ạa': xuất hiện 32 lần
Từ 'gã': xuất hiện 32 lần
Từ 'gô': xuất hiện 31 lần
Từ '6h': xuất hiện 31 lần
Từ 'ờ': xuất hiện 31 lần
Từ '1k': xuất hiện 31 lần
Từ 'rư': xuất hiện 31 lần
Từ 'cv': xuất hiện 31 lần
Từ 'tụ': xuất hiện 31 lần
Từ 'ts': xuất hiện 31 lần
Từ 'éo': xuất hiện 30 lần
Từ 'né': xuất hiện 30 lần
Từ 'rò': xuất hiện 30 lần
Từ '64': xuất hiện 30 lần
Từ '3g': xuất hiện 30 lần
Từ '7h': xuất hiện 30 lần
Từ '95': xuất hiện 30 lần
Từ 'ó': xuất hiện 30 lần
Từ 'ầm': xuất hiện 30 lần
Từ 'f9': xuất hiện 30 lần
Từ 'ib': xuất hiện 29 lần
Từ 'ml': xuất hiện 29 lần
Từ 'ps': xuất hiện 29 lần
Từ 'bk': xuất hiện 29 lần
Từ 'gđ': xuất hiện 29 lần
Từ 'mổ': xuất hiện 29 lần
Từ 'fx': xuất hiện 29 lần
Từ 'ik': xuất hiện 28 lần
Từ 'oh': xuất hiện 28 lần
Từ '49': xuất hiện 28 lần
Từ 'ră': xuất hiện 28 lần
Từ '34': xuất hiện 28 lần
Từ 'òi': xuất hiện 28 lần
Từ 't5': xuất hiện 28 lần
Từ 'xạ': xuất hiện 28 lần
Từ 'tẻ': xuất hiện 28 lần
Từ 'rù': xuất hiện 28 lần
Từ 'mc': xuất hiện 28 lần
Từ 'nu': xuất hiện 27 lần
Từ 'sk': xuất hiện 27 lần
Từ 'cự': xuất hiện 27 lần
Từ 'ùi': xuất hiện 27 lần
Từ 'hâ': xuất hiện 27 lần
Từ 'ắt': xuất hiện 27 lần
Từ '59': xuất hiện 27 lần
Từ 'ná': xuất hiện 26 lần
Từ 'hờ': xuất hiện 26 lần
Từ 'vò': xuất hiện 26 lần
Từ 'ớ': xuất hiện 25 lần
Từ 'mủ': xuất hiện 25 lần
Từ 'lh': xuất hiện 25 lần
Từ 'xó': xuất hiện 25 lần
Từ 'gư': xuất hiện 25 lần
Từ '75': xuất hiện 25 lần
Từ 'dỡ': xuất hiện 25 lần
Từ 'cb': xuất hiện 25 lần
Từ 'xư': xuất hiện 25 lần
Từ 'cớ': xuất hiện 25 lần
Từ 'sữ': xuất hiện 24 lần
Từ 'ạk': xuất hiện 24 lần
Từ '37': xuất hiện 24 lần
Từ 'pi': xuất hiện 24 lần
Từ 'ối': xuất hiện 24 lần
Từ 'lỳ': xuất hiện 24 lần
Từ 'dớ': xuất hiện 24 lần

In [ ]:
# Lặp lại nhiều lần để chuẩn hóa
import re

# 1. DANH SÁCH TỪ ĐIỂN (Key phải viết thường toàn bộ)
NORMALIZE_MAP = {
    "k": "không",
    "ko": "không",
    "kh": "không",
    "kg": "không",
    "dc": "được",
    "đc": "được",
    "sp": "sản_phẩm",
    "ng": "người",
    "ok": "ổn",
    "ad": "quản_trị_viên",
    "ib": "nhắn_tin",
    "rep": "trả_lời",
    "shop": "cửa_hàng",
    "mn": "mọi_người",
    "vs": "với",
    "mk": "mình",
    "r": "rồi",
    "khong": "không",
    "km": "Khuyến_mãi",
    "oke": "ổn",
    "oki": "ổn",
    "okê": "ổn",
    "ms": "mới",
    "cx": "cũng",
    "of": "của",
    "or": "hoặc",
    "sdt": "số_điện_thoại"

    # Bạn bổ sung thêm từ dựa trên kết quả của Phần 1
}

def normalize_text(text, norm_map):
    """
    Chuẩn hóa văn bản dựa trên từ điển map.
    """
    if not isinstance(text, str):
        return "" # Trả về chuỗi rỗng nếu dữ liệu lỗi

    # Bước 1: Chuyển toàn bộ về chữ thường
    text = text.lower()

    # Bước 2: Thay thế dấu câu bằng khoảng trắng để tách từ dính dấu
    # Ví dụ: "hàng ok,đẹp" -> "hàng ok đẹp"
    text = re.sub(r'[^\w\s]', ' ', text)

    # Bước 3: Tách từ ra thành list
    words = text.split()

    # Bước 4: So khớp và thay thế từ (Map lookup)
    # Nếu từ có trong map thì thay, không thì giữ nguyên
    new_words = [norm_map.get(w, w) for w in words]

    # Bước 5: Ghép lại thành câu
    return " ".join(new_words)

# --- CÁCH SỬ DỤNG ---
# Áp dụng hàm này vào cột dữ liệu
merged_df['content_text'] = (
    merged_df['content_text']
    .apply(lambda x: normalize_text(x, NORMALIZE_MAP))
)

# Kiểm tra kết quả
print("--- KẾT QUẢ SAU KHI CHUẨN HÓA ---")
merged_df[["content_text"]].head()

--- KẾT QUẢ SAU KHI CHUẨN HÓA ---

                                        content_text
0          xài êm làm sạch sâu không gây kích ứng da
1  sản phẩm được giao nhanh chóng đóng gói kỹ càn...
2                                               good
3  mình đã dùng chai thứ 2 rồi dùng cho tẩy trang...
4  không thích mùi này cảm giác như mùi men tuy n...

In [ ]:
def load_vietnamese_stopwords(path: str) -> set:
    """
    Load Vietnamese stopwords from .txt file
    Each stopword is on a separate line
    """
    with open(path, encoding='utf-8') as f:
        stopwords = {line.strip() for line in f if line.strip()}
    return stopwords

In [ ]:
def remove_vn_stopwords(text: str, stopword_set: set) -> str:
    """
    Remove Vietnamese stopwords from text
    - No tokenization library
    - No stemming
    - No word-length filtering
    """
    words = text.split()
    words = [w for w in words if w not in stopword_set]
    return " ".join(words)

In [ ]:
# Tải stopwords (chỉ thực hiện một lần)
vn_stopwords = load_vietnamese_stopwords(
    root_path + "vietnamese-stopwords.txt"
)

# Làm sạch văn bản
merged_df["content_text"] = merged_df["content_text"].apply(
    lambda x: remove_vn_stopwords(x, vn_stopwords)
)

# Xem trước một số văn bản đã làm sạch
merged_df[["content","content_text"]].head(10000).reset_index(drop=True)  # <--- khuyến khích xem nhiều lần để chuẩn hóa được dữ liệu

,content,content_text
0,"Xài êm, làm sạch sâu, không gây kích ứng da",xài êm làm sạch sâu không gây kích ứng da
1,"Sản phẩm được giao nhanh chóng, đóng gói kỹ cà...",sản phẩm được giao nhanh chóng đóng gói kỹ giá...
2,good,good
3,"Mình đã dùng chai thứ 2 rồi, dùng cho tẩy tran...",dùng chai 2 dùng tẩy trang nhẹ không gây khô d...
4,"k thích mùi này , cảm giác như mùi men tuy nh...",không thích mùi cảm giác mùi men nhiên tẩy tra...
...,...,...
9995,"Tinh dầu thơm dễ chịu, massage xong để nguyên ...",tinh dầu thơm dễ chịu massage xong nguyên tinh...
9996,"Sản phẩm dùng tốt, thơm. Đóng gói rất cẩn thậ...",sản phẩm dùng tốt thơm đóng gói rất cẩn thận m...
9997,"Giao nhanh, Tiki đóng gói đẹp, chưa sử dụng.",giao nhanh tiki đóng gói đẹp chưa sử dụng
9998,Tinh dầu dùng tốt,tinh dầu dùng tốt
9999,Dùng ok,dùng ổn

#5. Tạo các đặc trưng dựa theo các tiêu chí để chuẩn bị gán nhãn

##5.1. Hành vi đánh giá ồ ạt

In [ ]:
# sắp xếp theo user và thời gian
merged_df = merged_df.sort_values(['customer_id', 'created_at'])

# tính khoảng cách giữa 2 comment liên tiếp của cùng user
merged_df['delta_minutes'] = (
    merged_df
        .groupby('customer_id')['created_at']
        .diff()
        .dt.total_seconds() / 60
)

valid_delta = merged_df.loc[
    merged_df['delta_minutes'] > 0,
    'delta_minutes'
]

threshold_burst = valid_delta.quantile(0.05)

print("Ngưỡng burst (phút):", threshold_burst)

Ngưỡng burst (phút): 0.15

In [ ]:
# lấy ngưỡng khoảng cách bất thường giữa 2 cmt là 5% khoảng cách ngắn nhất giữa 2 lần cmt đã tổng hợp ở trên
threshold_burst = merged_df['delta_minutes'].quantile(0.05)
print("Ngưỡng burst (phút):", threshold_burst)

Ngưỡng burst (phút): 0.15

In [ ]:
# Xác định những khoảng nhỏ là những dấu hiệu về một bình luận bất thường
merged_df['small_gap'] = merged_df['delta_minutes'] <= threshold_burst

In [ ]:
# Góm nhóm những lần bất thường của các bình luận và đếm
merged_df['burst_count'] = (
    merged_df.groupby('customer_id')['small_gap']
    .transform(lambda x: x * (x.groupby((x != x.shift()).cumsum()).cumcount() + 1))
)

In [ ]:
# Xác định và nghi ngờ những bình luận đó có phải là gian lận hay không bằng cách đếm xem nếu có lơn hơn hoặc bằng 4 lần diễn ra các khoảng nhỏ diễn ra liên tiếp nhau
merged_df['F3_flag'] = merged_df['burst_count'] >= 4

In [ ]:
# 1. Lấy danh sách user đã từng bị gắn cờ F3
fraud_users = merged_df.loc[
    merged_df['F3_flag'] == True,
    'customer_id'
].unique()

# 2. Lọc toàn bộ comment của những user đó
result = (
    merged_df[merged_df['customer_id'].isin(fraud_users)]
    [['customer_id',
      'created_at',
      'purchased_at',
      'delta_minutes',
      'burst_count',
      'F3_flag']]
    .sort_values(['customer_id', 'created_at'])
)

# 3. In 15 dòng đầu
# Kết quả nó sẽ hiện những lần cmt của các user đã bị gắn cờ gian lận và hiện từ lúc mà burst count từ 0 đến 4
print(result.head(50))

        customer_id          created_at        purchased_at  delta_minutes  \
28358        276301 2021-08-07 16:24:23 2021-06-09 02:15:53            NaN
16582        276301 2021-08-07 16:24:28 2021-06-09 02:15:53       0.083333
13953        276301 2021-08-07 16:24:34 2021-06-09 02:15:53       0.100000
46486        276301 2021-08-07 16:24:39 2021-06-09 02:15:53       0.083333
4320         276301 2021-08-07 16:24:44 2021-06-09 02:15:53       0.083333
177324       784170 2023-01-13 11:04:22 2023-01-08 13:48:59            NaN
147416       784170 2023-01-13 11:04:37 2022-11-11 09:59:38       0.250000
160690       784170 2023-01-13 11:04:41 2023-12-30 06:29:07       0.066667
121079       784170 2023-01-13 11:04:44 2022-11-11 09:59:38       0.050000
99695        784170 2023-01-13 11:04:52 2022-11-11 09:59:38       0.133333
171482       784170 2023-01-13 11:04:58 2022-10-29 08:48:43       0.100000
12026       1152608 2021-01-15 16:16:11 2021-01-04 11:59:03            NaN
5074        1152608 2021-01-15 16:16:19 2021-01-04 11:59:03       0.133333
12234       1152608 2021-06-26 02:30:27 2021-06-25 10:51:36  232454.133333
28365       1152608 2021-06-26 02:30:31 2021-06-25 10:51:36       0.066667
13962       1152608 2021-06-26 02:30:32 2021-06-25 10:51:36       0.016667
16594       1152608 2021-06-26 02:30:33 2021-06-25 10:51:36       0.016667
12094       1152608 2021-06-26 02:30:34 2021-03-26 03:50:59       0.016667
15926       1152608 2021-06-26 02:30:36 2021-03-26 03:50:59       0.033333
293573      1152608 2021-08-11 02:39:29 2021-08-10 15:13:08   66248.883333
14238       1467047 2022-11-23 15:00:45 2022-11-17 07:32:30            NaN
4212        1467047 2022-11-23 15:00:49 2022-11-17 07:32:30       0.066667
205481      1467047 2022-11-23 15:00:56 2022-10-22 07:59:19       0.116667
144404      1467047 2022-11-23 15:01:03 2022-10-22 07:59:19       0.116667
224135      1467047 2022-11-23 15:01:07 2022-10-22 07:59:19       0.066667
97001       5213589 2021-04-02 08:57:59 2021-03-17 06:57:29            NaN
151610      5213589 2021-04-02 08:58:24 2021-03-17 06:57:29       0.416667
174284      5213589 2021-11-10 07:57:30 2021-11-05 12:17:34  319619.100000
158050      5213589 2021-11-10 07:57:36 2021-11-05 12:17:34       0.100000
177481      5213589 2021-11-10 07:57:37 2021-11-05 12:17:34       0.016667
221347      5213589 2021-11-10 07:57:38 2021-11-05 12:17:34       0.016667
127721      5213589 2021-11-10 07:57:40 2022-06-12 16:49:30       0.033333
217414      5213589 2021-11-10 07:57:45 2021-11-05 12:17:34       0.083333
166496      5213589 2022-01-14 01:57:12 2022-01-11 06:05:12   93239.450000
160709      5213589 2022-06-16 01:53:33 2022-06-12 16:49:30  220316.350000
123682      5213589 2022-06-16 01:54:18 2022-06-12 16:49:30       0.750000
227492      5213589 2022-07-08 02:25:49 2022-07-05 23:10:30   31711.516667
287930      5213589 2022-08-19 07:35:47 2022-08-09 07:58:26   60789.966667
23578       5213589 2022-09-07 09:10:34 2022-08-31 07:14:33   27454.783333
328513      5213589 2022-09-07 09:10:50 2022-08-31 07:14:33       0.266667
333187      5213589 2022-09-25 15:19:19 2022-08-31 07:34:20   26288.483333
29287       5213589 2022-10-23 14:14:02 2022-10-19 02:16:49   40254.716667
287273      5213589 2022-10-26 10:17:07 2022-10-24 08:50:57    4083.083333
292876      5213589 2022-11-07 06:45:37 2022-11-05 12:47:30   17068.500000
187236      5213589 2023-01-06 11:30:25 2023-01-04 10:41:31   86684.800000
83197       5213589 2023-03-03 14:48:16 2023-02-28 02:28:11   80837.850000
77160       5213589 2023-03-03 14:48:22 2023-02-22 00:33:04       0.100000
318061      5213589 2023-03-03 14:48:27 2023-02-21 05:00:33       0.083333
17150       5213589 2023-03-11 10:47:17 2023-03-07 00:30:44   11278.833333
47920       5213589 2023-04-07 15:28:39 2023-04-03 10:22:52   39161.366667

        burst_count  F3_flag
28358             0    False
16582             1    False
13953             2    False
46486             3    False
4320              4     True
177324            0    False
147416            0    False
160690            1    False
121079            2    False
99695             3    False
171482            4     True
12026             0    False
5074              1    False
12234             0    False
28365             1    False
13962             2    False
16594             3    False
12094             4     True
15926             5     True
293573            0    False
14238             0    False
4212              1    False
205481            2    False
144404            3    False
224135            4     True
97001             0    False
151610            0    False
174284            0    False
158050            1    False
177481            2    False
221347            3    False
127721            4     True
217414            5     True
166496            0    False
160709            0    False
123682            0    False
227492            0    False
287930            0    False
23578             0    False
328513            0    False
333187            0    False
29287             0    False
287273            0    False
292876            0    False
187236            0    False
83197             0    False
77160             1    False
318061            2    False
17150             0    False
47920             0    False

##5.2. Sự tương đồng về nội dung

In [ ]:
# Gom nhóm comment theo customer_id
user_comments = merged_df.groupby("customer_id", sort=False)["content"].apply(list).reset_index()

# In 5 dòng đầu của bảng sau khi gom
print(user_comments.head())

# Xem chi tiết comment của customer id đầu tiên
print("\nCustomer ID:", user_comments.loc[0, "customer_id"])
print("Danh sách comment:")

for cmt in user_comments.loc[0, "content"]:
    print("-", cmt)

   customer_id                                            content
0           27  [Giá giảm 50%. Cái gáy sách hơi nát nhưng thôi...
1           36  [Sản phẩm có giá thành và chất lượng rất hợp l...
2           38  [Giao hàng siêu nhanh. Nhưng thấy ghi giảm 12%...
3           39         [Tiki bán rẻ hơn chỗ khác. Chất lượng tốt]
4           99  [Nhận được sách bóc hộp ra chả biết nói gì nữa...

Customer ID: 27
Danh sách comment:
- Giá giảm 50%. Cái gáy sách hơi nát nhưng thôi mình dễ tính nên cũng chấp nhận thôi.
- Mình thích dòng sản phẩm sữa rửa mặt của Senka từ khi học ở Nhật nhưng chưa dùng thử dòng trị mụn này bao giờ. Mong là sử dụng tốt. Hàng giao nhanh và giống miêu tả
- Nói chung là gia sư của mình khuyến khích dùng cuốn này nên mình mua. Đọc sơ qua thấy cũng được. Chất lượng bảo quản sách của Tiki ok. Xíu phải mua thêm một cuốn cho con em.
- Mua giùm cho bé em bên nhà cung cấp Fahasa. Bảo quản sách tốt, nội dung mình chưa rõ.
- Chỉ có thể nói là đỉnh. Các trận chiến càng ngày càng hay.

In [ ]:
# Tạo cột và tính giá trị
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# tạo 2 cột mới
user_comments["mean_similarity"] = np.nan
user_comments["max_similarity"] = np.nan
vectorizer = TfidfVectorizer()

#tính mean,max
for i in range(len(user_comments)):
    comments = user_comments.loc[i, "content"]
    # loại comment rỗng
    comments = [c for c in comments if isinstance(c, str) and c.strip() != ""]
    # nếu user có <2 comment thì bỏ qua
    if len(comments) < 2:
        continue
    try:
        tfidf = vectorizer.fit_transform(comments)
        sim_matrix = cosine_similarity(tfidf)
        sim_values = sim_matrix[np.triu_indices_from(sim_matrix, k=1)]
        user_comments.loc[i, "mean_similarity"] = sim_values.mean()
        user_comments.loc[i, "max_similarity"] = sim_values.max()
    except:
        continue
# in kết quả
print(user_comments.head())

   customer_id                                            content  \
0           27  [Giá giảm 50%. Cái gáy sách hơi nát nhưng thôi...
1           36  [Sản phẩm có giá thành và chất lượng rất hợp l...
2           38  [Giao hàng siêu nhanh. Nhưng thấy ghi giảm 12%...
3           39         [Tiki bán rẻ hơn chỗ khác. Chất lượng tốt]
4           99  [Nhận được sách bóc hộp ra chả biết nói gì nữa...

   mean_similarity  max_similarity
0         0.063462        0.211732
1              NaN             NaN
2              NaN             NaN
3              NaN             NaN
4              NaN             NaN

In [ ]:
#Xác định ngưỡng
import numpy as np

# Bỏ các user không tính được similarity
valid_users = user_comments.dropna(subset=["mean_similarity", "max_similarity"])

# Tính mean,max và std của toàn dataset
mean_mean = valid_users["mean_similarity"].mean()
std_mean = valid_users["mean_similarity"].std()

mean_max = valid_users["max_similarity"].mean()
std_max = valid_users["max_similarity"].std()

# Tính ngưỡng
threshold_mean = mean_mean + std_mean
threshold_max = mean_max + std_max

# In kết quả
print("\nNgưỡng phát hiện spam:")
print("Threshold mean =", threshold_mean)
print("Threshold max =", threshold_max)

Ngưỡng phát hiện spam:
Threshold mean = 0.5108772642580244
Threshold max = 0.6766562385306101

In [ ]:
# Gán nhãn
user_comments["F4_Flag"] = (
    (user_comments["mean_similarity"] >= threshold_mean) |
    (user_comments["max_similarity"] >= threshold_max)
)

# in 15 dòng đầu và hiển thị tất cả cột
print(user_comments.head(15))

    customer_id                                            content  \
0            27  [Giá giảm 50%. Cái gáy sách hơi nát nhưng thôi...
1            36  [Sản phẩm có giá thành và chất lượng rất hợp l...
2            38  [Giao hàng siêu nhanh. Nhưng thấy ghi giảm 12%...
3            39         [Tiki bán rẻ hơn chỗ khác. Chất lượng tốt]
4            99  [Nhận được sách bóc hộp ra chả biết nói gì nữa...
5           125                [hàng chấp nhận được trong tầm giá]
6           167  [Dùng rất thích, tẩy xong da mặt sạch bong, ko...
7           192  [tuýp 40ml, giao hàng nhanh - đóng gói cẩn thậ...
8           200  [“Measure What Matters” của John Doerr là một ...
9           247  [Rẻ và tiện, Lolz tưởng nó là gì hoá ra bao đủ...
10          278  [Nội dung được nhưng hơi ít ý, xoay đi xoay lạ...
11          279                        [Sản phẩm trị gàu rất tốt.]
12          347                                 [Sách hay nên đọc]
13          349  [Tất cả điều hài lòng ngoại trừ một điểm lớn l...
14          351  [Mình mới dùng sản phẩm này được gần nửa tháng...

    mean_similarity  max_similarity  F4_Flag
0          0.063462        0.211732    False
1               NaN             NaN    False
2               NaN             NaN    False
3               NaN             NaN    False
4               NaN             NaN    False
5               NaN             NaN    False
6               NaN             NaN    False
7               NaN             NaN    False
8               NaN             NaN    False
9          0.010345        0.207935    False
10              NaN             NaN    False
11              NaN             NaN    False
12              NaN             NaN    False
13         0.000000        0.000000    False
14              NaN             NaN    False

In [ ]:
merged_df = merged_df.merge(
    user_comments[["customer_id", "mean_similarity", "max_similarity", "F4_Flag"]],
    on="customer_id",
    how="left"
)

print(merged_df.head())

   comment_id   product_id  customer_id         customer_name  rating  \
0     6017420   23413038.0           27  Vũ Hương Quỳnh Trang       4
1     6627156   33785195.0           27  Vũ Hương Quỳnh Trang       5
2     7260004    8121460.0           27  Vũ Hương Quỳnh Trang       5
3     7314188    8121460.0           27  Vũ Hương Quỳnh Trang       5
4    14157600  147931870.0           27  Vũ Hương Quỳnh Trang       5

             title                                            content  \
0         Hài lòng  Giá giảm 50%. Cái gáy sách hơi nát nhưng thôi ...
1  Cực kì hài lòng  Mình thích dòng sản phẩm sữa rửa mặt của Senka...
2  Cực kì hài lòng  Nói chung là gia sư của mình khuyến khích dùng...
3  Cực kì hài lòng  Mua giùm cho bé em bên nhà cung cấp Fahasa. Bả...
4  Cực kì hài lòng  Chỉ có thể nói là đỉnh. Các trận chiến càng ng...

           created_at        purchased_at  seller_id           seller_name  \
0 2020-12-07 15:57:23 2020-12-04 18:24:24        1.0          Tiki Trading
1 2020-12-30 20:35:18 2020-12-29 17:23:46     6423.0  Senka Official Store
2 2021-01-26 05:50:46 2021-01-25 17:46:52        1.0          Tiki Trading
3 2021-01-28 04:33:48 2021-01-26 08:24:13    53660.0       Nhà sách Fahasa
4 2021-12-30 02:47:18 2021-12-27 02:38:13        1.0          Tiki Trading

                                        product_name  \
0              Sách Mãi Mãi Là Bao Xa (Tái Bản 2019)
1  Sữa rửa mặt hỗ trợ trị mụn Senka Perfect Whip ...
2  Sách Giáo Trình Hán Ngữ 1 - Tập 1 - Quyển Thượ...
3  Sách Giáo Trình Hán Ngữ 1 - Tập 1 - Quyển Thượ...
4                                         Kingdom 18

                                        content_text  delta_minutes  \
0          giá giảm 50 gáy sách hơi nát dễ chấp nhận            NaN
1  thích dòng sản phẩm sữa rửa mặt senka học nhật...   33397.916667
2  nói gia sư khuyến khích dùng cuốn mua đọc sơ đ...   37995.466667
3  mua giùm bé cung cấp fahasa bảo quản sách tốt ...    2803.033333
4                     chỉ có thể nói đỉnh trận chiến  483733.500000

   small_gap  burst_count  F3_flag  mean_similarity  max_similarity  F4_Flag
0      False            0    False         0.063462        0.211732    False
1      False            0    False         0.063462        0.211732    False
2      False            0    False         0.063462        0.211732    False
3      False            0    False         0.063462        0.211732    False
4      False            0    False         0.063462        0.211732    False

## 5.3. Bất thường về độ trễ thời gian

In [ ]:
# Tính khoảng cách thời gian giữa mua và đánh giá (phút)
merged_df['time_gap_minutes'] = (
    (merged_df['created_at'] - merged_df['purchased_at'])
    .dt.total_seconds() / 60
)

# Loại bỏ các giá trị âm (nếu có lỗi data)
valid_gap = merged_df.loc[
    merged_df['time_gap_minutes'] > 0,
    'time_gap_minutes'
]

In [ ]:
# Xác định ngưỡng bất thường (5% nhỏ nhất)
threshold_timegap = valid_gap.quantile(0.05)

print("Ngưỡng time-gap bất thường (phút):", threshold_timegap)

#  Gắn cờ F5
merged_df['F5_flag'] = (
    merged_df['time_gap_minutes'] > 0
) & (
    merged_df['time_gap_minutes'] <= threshold_timegap
)

Ngưỡng time-gap bất thường (phút): 1020.7266666666668

In [ ]:
# Lấy danh sách user đã từng bị gắn cờ F5
fraud_users_F5 = merged_df.loc[
    merged_df['F5_flag'] == True,
    'customer_id'
].unique()

# Lọc toàn bộ comment của những user đó
result_F5 = (
    merged_df[merged_df['customer_id'].isin(fraud_users_F5)]
    [['customer_id',
      'created_at',
      'purchased_at',
      'time_gap_minutes',
      'F5_flag']]
    .sort_values(['customer_id', 'created_at'])
)

#  In 50 dòng đầu
print(result_F5.head(50))

     customer_id          created_at        purchased_at  time_gap_minutes  \
0             27 2020-12-07 15:57:23 2020-12-04 18:24:24       4172.983333
1             27 2020-12-30 20:35:18 2020-12-29 17:23:46       1631.533333
2             27 2021-01-26 05:50:46 2021-01-25 17:46:52        723.900000
3             27 2021-01-28 04:33:48 2021-01-26 08:24:13       2649.583333
4             27 2021-12-30 02:47:18 2021-12-27 02:38:13       4329.083333
6             38 2022-08-28 03:01:37 2022-08-27 21:45:46        315.850000
8             99 2018-10-09 14:17:41 2018-10-09 10:49:08        208.550000
9            125 2021-10-12 04:48:28 2021-10-11 13:20:29        927.983333
13           247 2021-05-22 08:24:32 2021-03-11 09:35:51     103608.683333
14           247 2021-05-26 01:57:50 2021-04-23 09:23:43      47074.116667
15           247 2021-05-30 23:00:48 2021-04-23 09:23:43      54097.083333
16           247 2021-06-01 12:47:37 2021-06-01 03:52:35        535.033333
17           247 2021-06-05 13:11:39 2021-06-04 06:11:17       1860.366667
18           247 2021-06-06 04:28:05 2021-05-30 13:26:14       9541.850000
19           247 2021-07-01 23:41:59 2021-07-01 08:08:50        933.150000
20           247 2022-05-05 10:22:01 2022-05-05 02:14:27        487.566667
59           742 2023-06-14 15:48:54 2023-06-14 08:06:15        462.650000
155         2256 2018-08-10 14:11:50 2018-08-10 09:56:28        255.366667
156         2321 2021-05-29 02:21:24 2021-05-28 13:43:54        757.500000
157         2321 2021-09-09 23:39:42 2021-08-22 00:27:05      27312.616667
165         2425 2021-12-06 09:53:34 2021-12-05 17:56:36        956.966667
166         2426 2020-02-23 23:49:42 2020-02-20 10:30:18       5119.400000
167         2426 2021-03-20 09:15:30 2021-03-18 02:12:28       3303.033333
168         2426 2021-06-11 01:51:28 2021-06-09 10:17:26       2374.033333
169         2426 2021-09-16 04:34:09 2021-09-08 09:19:19      11234.833333
170         2426 2022-03-09 03:53:49 2022-03-07 04:56:20       2817.483333
171         2426 2022-04-09 01:56:08 2022-04-06 09:44:34       3851.566667
172         2426 2022-04-12 01:16:17 2022-04-12 00:00:48         75.483333
173         2426 2022-05-18 01:59:29 2022-05-15 23:38:04       3021.416667
174         2426 2022-12-03 04:42:49 2022-12-01 00:42:42       3120.116667
175         2426 2023-09-20 01:59:51 2023-09-17 23:39:32       3020.316667
184         2584 2021-10-30 03:11:29 2021-10-29 10:14:27       1017.033333
203         2936 2018-10-09 14:12:30 2018-10-09 10:33:34        218.933333
204         2936 2020-10-19 14:26:23 2020-10-18 08:03:03       1823.333333
205         2936 2021-06-05 16:59:51 2021-04-29 10:10:48      53689.050000
206         2936 2021-07-06 06:26:27 2021-07-01 07:06:14       7160.216667
207         2936 2021-08-26 06:57:56 2021-08-23 07:53:49       4264.116667
208         2936 2021-10-23 12:44:07 2021-10-04 17:00:10      27103.950000
209         2936 2022-04-21 13:18:12 2022-04-17 03:13:44       6364.466667
210         2936 2022-05-06 12:29:29 2022-04-30 08:33:07       8876.366667
211         2936 2022-07-28 08:54:39 2022-06-20 06:42:56      54851.716667
212         2936 2022-07-28 08:54:56 2022-06-20 06:40:23      54854.550000
250         3440 2022-03-05 03:33:38 2022-03-04 11:06:50        986.800000
264         3606 2021-03-07 01:53:15 2021-02-23 04:38:17      17114.966667
265         3606 2021-06-15 05:46:06 2021-06-15 03:25:43        140.383333
266         3606 2021-07-08 07:12:35 2021-07-08 04:18:18        174.283333
267         3606 2021-08-08 05:02:42 2021-08-08 02:08:35        174.116667
271         3646 2019-06-20 12:24:28 2019-06-20 08:58:27        206.016667
272         3646 2020-03-06 06:59:33 2020-03-04 11:44:39       2594.900000
273         3646 2021-10-10 03:48:27 2021-10-03 13:57:33       9470.900000

     F5_flag
0      False
1      False
2       True
3      False
4      False
6       True
8       True
9       True
13     False
14     False
15     False
16      True
17     False
18     False
19      True
20      True
59      True
155     True
156     True
157    False
165     True
166    False
167    False
168    False
169    False
170    False
171    False
172     True
173    False
174    False
175    False
184     True
203     True
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
250     True
264    False
265     True
266     True
267     True
271     True
272    False
273    False

In [ ]:
merged_df

,comment_id,product_id,customer_id,customer_name,rating,title,content,created_at,purchased_at,seller_id,...,content_text,delta_minutes,small_gap,burst_count,F3_flag,mean_similarity,max_similarity,F4_Flag,time_gap_minutes,F5_flag
0,6017420,23413038.0,27,Vũ Hương Quỳnh Trang,4,Hài lòng,Giá giảm 50%. Cái gáy sách hơi nát nhưng thôi ...,2020-12-07 15:57:23,2020-12-04 18:24:24,1.0,...,giá giảm 50 gáy sách hơi nát dễ chấp nhận,NaN,False,0,False,0.063462,0.211732,False,4172.983333,False
1,6627156,33785195.0,27,Vũ Hương Quỳnh Trang,5,Cực kì hài lòng,Mình thích dòng sản phẩm sữa rửa mặt của Senka...,2020-12-30 20:35:18,2020-12-29 17:23:46,6423.0,...,thích dòng sản phẩm sữa rửa mặt senka học nhật...,33397.916667,False,0,False,0.063462,0.211732,False,1631.533333,False
2,7260004,8121460.0,27,Vũ Hương Quỳnh Trang,5,Cực kì hài lòng,Nói chung là gia sư của mình khuyến khích dùng...,2021-01-26 05:50:46,2021-01-25 17:46:52,1.0,...,nói gia sư khuyến khích dùng cuốn mua đọc sơ đ...,37995.466667,False,0,False,0.063462,0.211732,False,723.900000,True
3,7314188,8121460.0,27,Vũ Hương Quỳnh Trang,5,Cực kì hài lòng,Mua giùm cho bé em bên nhà cung cấp Fahasa. Bả...,2021-01-28 04:33:48,2021-01-26 08:24:13,53660.0,...,mua giùm bé cung cấp fahasa bảo quản sách tốt ...,2803.033333,False,0,False,0.063462,0.211732,False,2649.583333,False
4,14157600,147931870.0,27,Vũ Hương Quỳnh Trang,5,Cực kì hài lòng,Chỉ có thể nói là đỉnh. Các trận chiến càng ng...,2021-12-30 02:47:18,2021-12-27 02:38:13,1.0,...,chỉ có thể nói đỉnh trận chiến,483733.500000,False,0,False,0.063462,0.211732,False,4329.083333,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320677,20201874,653804.0,30575426,Hoàng Quốc Đông,2,Không hài lòng,Chưa hài lòng lắm về quy cách đóng gói,2025-12-29 10:20:59,2025-12-25 06:31:12,1.0,...,chưa hài lòng lắm quy cách đóng gói,NaN,False,0,False,NaN,NaN,False,5989.783333,False
320678,20202892,277397107.0,30575925,Phạm Ngọc Minh Thanh,5,Cực kì hài lòng,"Đóng gói kĩ, giáo hàng nhanh, sách đẹp",2026-01-02 16:39:55,2025-12-30 07:22:44,1.0,...,đóng gói kĩ giáo hàng nhanh sách đẹp,NaN,False,0,False,NaN,NaN,False,4877.183333,False
320679,20201812,277397107.0,30576438,Lê Ngọc Phúc,1,Rất không hài lòng,"Sách bị bẩn rách, góc sách còn bị nát còn khô...",2025-12-29 05:59:41,2025-12-23 12:07:36,1.0,...,sách bị bẩn rách góc sách còn bị nát còn không...,NaN,False,0,False,0.248318,0.248318,False,8272.083333,False
320680,20201814,249876840.0,30576438,Lê Ngọc Phúc,5,Cực kì hài lòng,Sách đẹp có seal đàng hoàng,2025-12-29 06:05:20,2025-12-23 12:15:40,1.0,...,sách đẹp có seal đàng hoàng,5.650000,False,0,False,0.248318,0.248318,False,8269.666667,False
320681,20202832,257857032.0,30583205,Huy T,5,Cực kì hài lòng,"Sản phẩm đúng mô tả, chi tiết kỹ thuật trên vỏ...",2026-01-02 10:53:17,2026-01-02 06:35:27,1.0,...,sản phẩm đúng mô tả chi tiết kỹ thuật vỏ hộp c...,NaN,False,0,False,NaN,NaN,False,257.833333,True

In [ ]:
# Lưu file vào drive
merged_df.to_csv("/content/drive/MyDrive/big_data/phan_1/data/merged_df.csv", index=False)

#6. Chọn ra 10% dữ liệu

In [ ]:
# Lọc spam và ham theo đúng logic
spam_df = merged_df[
    (merged_df["F3_flag"] == True) |
    (merged_df["F4_Flag"] == True) |
    (merged_df["F5_flag"] == True)
]

ham_df = merged_df[
    (merged_df["F3_flag"] == False) &
    (merged_df["F4_Flag"] == False) &
    (merged_df["F5_flag"] == False)
]

# Tính số lượng cần lấy cho 10% tổng dữ liệu
sample_size = int(len(merged_df) * 0.1)
sample_per_class = sample_size // 2  # Chia đều cho spam và ham

# Lấy mẫu cân bằng
spam_sample = spam_df.sample(n=min(sample_per_class, len(spam_df)), random_state=42)
ham_sample = ham_df.sample(n=min(sample_per_class, len(ham_df)), random_state=42)

# Kết hợp và xáo trộn
final_df = pd.concat([spam_sample, ham_sample]).sample(frac=1, random_state=42)

path = "/content/drive/MyDrive/big_data/phan_1/data/10%_dataset.csv"
final_df.to_csv(path, index=False)